replicaCount: 1

image:
  repository: accounts-service
  tag: 1.0-SNAPSHOT
  pullPolicy: IfNotPresent

service:
  port: 8083

config:
  KEYCLOAK_URL: http://keycloak:8080
  AUTHORIZATION_URI: http://localhost:8080/realms/Bank-app/protocol/openid-connect/auth
  JWK_SET_URI: http://keycloak:8080/realms/Bank-app/protocol/openid-connect/certs
  TOKEN_URI: http://keycloak:8080/realms/Bank-app/protocol/openid-connect/token
  REALM_NAME: Bank-app
  ACCOUNTS_DB_URL: r2dbc:postgresql://accounts-db:5432/bank
  ACCOUNTS_DB_NAME: bank
  ACCOUNTS_DB_USER: user
  GATEWAY_URL: http://api-gateway:8090/

secrets:
  ACCOUNTS_DB_PASSWORD: "12345"
  ACCOUNTS_CLIENT_SECRET: wXm9jO5pvKvDcIvheI6HRrVJgGuZboVS

postgresql:
  name: accounts-db
  port: 5432
  replicaCount: 1
  image:
    repository: postgres
    tag: 17-alpine