spring:
  application:
    name: notification-service
  r2dbc:
    url: r2dbc:postgresql://notification-db:5432/notification
    username: user
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka