DROP TABLE IF EXISTS notifications;

CREATE TABLE IF NOT EXISTS notifications
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    username VARCHAR(255)                            NOT NULL,
    message  VARCHAR(255)                            NOT NULL,
    type     VARCHAR(255)                            NOT NULL,
    showed   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_notification PRIMARY KEY (id)
);