logstash:
  fullnameOverride: logstash
  logstashPipeline:
    logstash.conf: |
      input {
        kafka {
          bootstrap_servers => "kafka:9092"
          topics => ["bank-logs"]
          group_id => "bank-group"
          decorate_events => extended
        }
      }
      filter {
        grok {
          match => {
            "message" => "%{TIME:log_time} \[%{DATA:service}\] %{LOGLEVEL:level} ?: %{GREEDYDATA:msg_body}"
            }
          }
        grok {
          match => {
            "msg_body" => "username: %{WORD:username}"
          }
          tag_on_failure => []
        }
      date {
        match => ["log_time", "HH:mm:ss.SSS"]
          target => "@timestamp"
        }
      }
      output {
        elasticsearch {
          hosts => ["http://elasticsearch:9200"]
          index => "logs-%{+dd.MM.YYYY}"
          retry_on_conflict => 3
          action => "index"
        }
      }