apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-service.fullname" . }}-config
data:
  JWK_SET_URI: {{ .Values.config.JWK_SET_URI | quote }}
  EXCHANGE_REDIS_HOST: {{ .Values.config.EXCHANGE_REDIS_HOST | quote }}
  EXCHANGE_REDIS_PORT: {{ .Values.config.EXCHANGE_REDIS_PORT | quote }}