version: '3.8'
services:
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  exchange-service:
    build:
      context: ./exchange-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - redis
  accounts-service:
    build:
      context: ./accounts-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - accounts-db
  exchange-generator-service:
    build:
      context: ./exchange-generator-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - exchange-service
  frontend-service:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
  cash-service:
    build:
      context: ./cash-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
  redis:
    image: redis:8.0-M04-bookworm
    ports:
      - "6379:6379"
  accounts-db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - exchange-service
      - exchange-generator-service
      - discovery-service
      - accounts-service
      - frontend-service
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    ports:
      - "9081:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    command: start-dev --import-realm
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 4s