spring:
  application:
    name: exchange-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
  data:
    redis:
      host: ${EXCHANGE_REDIS_HOST}
      port: ${EXCHANGE_REDIS_PORT}
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: exchange-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
server:
  port: 8082