spring:
  application:
    name: exchange-service
  data:
    redis:
      host: redis
      port: 6379
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka