spring:
  application:
    name: exchange-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
  data:
    redis:
      host: ${EXCHANGE_REDIS_HOST}
      port: ${EXCHANGE_REDIS_PORT}
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: bank-kafka
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.type: java.util.List<ru.practicum.model.dto.RateDto>
server:
  port: 8082
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: prometheus