server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/api/rates/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka