apiVersion: v2
name: elasticsearch
description: elasticsearch  Helm chart
type: application
version: 0.1.0
appVersion: "4.0.0"

dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co