apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts-service.fullname" . }}-config
data:
  KEYCLOAK_URL: {{ .Values.config.KEYCLOAK_URL | quote }}
  AUTHORIZATION_URI: {{ .Values.config.AUTHORIZATION_URI | quote }}
  JWK_SET_URI: {{ .Values.config.JWK_SET_URI | quote }}
  TOKEN_URI: {{ .Values.config.TOKEN_URI | quote }}
  REALM_NAME: {{ .Values.config.REALM_NAME | quote }}
  ACCOUNTS_DB_URL: {{ .Values.config.ACCOUNTS_DB_URL | quote }}
  ACCOUNTS_DB_NAME: {{ .Values.config.ACCOUNTS_DB_NAME | quote }}
  ACCOUNTS_DB_USER: {{ .Values.config.ACCOUNTS_DB_USER | quote }}
  GATEWAY_URL: {{ .Values.config.GATEWAY_URL | quote }}
  POSTGRES_DB: {{ .Values.config.ACCOUNTS_DB_NAME | quote }}
  POSTGRES_USER: {{ .Values.config.ACCOUNTS_DB_USER | quote }}
  ZIPKIN_URL: {{.Values.config.ZIPKIN_URL | quote}}