apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts-service.fullname" . }}-secret
type: Opaque
stringData:
  ACCOUNTS_DB_PASSWORD: {{ .Values.secrets.ACCOUNTS_DB_PASSWORD | quote }}
  ACCOUNTS_CLIENT_SECRET: {{ .Values.secrets.ACCOUNTS_CLIENT_SECRET | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.ACCOUNTS_DB_PASSWORD | quote }}