spring:
  application:
    name: cash-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
      client:
        provider:
          keycloak:
            jwk-set-uri: ${JWK_SET_URI}
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
        registration:
          cash-service:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: cash-service
            client-secret: ${CASH_CLIENT_SECRET}
            scope: profile, openid
            clientAuthenticationMethod: client_secret_post
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 30000
gateway:
  url: ${GATEWAY_URL}
server:
  port: 8085
