spring:
  application:
    name: exchange-generator-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            jwk-set-uri: http://keycloak:8080/realms/Bank-app/protocol/openid-connect/certs
            authorization-uri: http://localhost:8080/realms/Bank-app/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/Bank-app/protocol/openid-connect/token
        registration:
          exchange-generator-service:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: exchange-generator-service
            client-secret: vHZgqEibJa1zPFvCKTVGtw0C4lMIWlFi
            scope: profile, openid
            clientAuthenticationMethod: client_secret_post
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka