apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transfer-service.fullname" . }}-secret
type: Opaque
stringData:
  TRANSFER_CLIENT_SECRET: {{ .Values.secrets.TRANSFER_CLIENT_SECRET | quote }}