apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification-service.fullname" . }}-config
data:
  JWK_SET_URI: {{ .Values.config.JWK_SET_URI | quote }}
  NOTIFICATION_DB_URL: {{ .Values.config.NOTIFICATION_DB_URL | quote }}
  NOTIFICATION_DB_NAME: {{ .Values.config.NOTIFICATION_DB_NAME | quote }}
  NOTIFICATION_DB_USER: {{ .Values.config.NOTIFICATION_DB_USER | quote }}
  POSTGRES_DB: {{ .Values.config.NOTIFICATION_DB_NAME | quote }}
  POSTGRES_USER: {{ .Values.config.NOTIFICATION_DB_USER | quote }}