apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresql.name }}
spec:
  serviceName: {{ .Values.postgresql.name }}
  replicas: {{ .Values.postgresql.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgresql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.name }}
    spec:
      containers:
        - name: {{ .Values.postgresql.name }}
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          ports:
            - containerPort: {{ .Values.postgresql.port }}
          envFrom:
            - configMapRef:
                name: {{ include "notification-service.fullname" . }}-config
            - secretRef:
                name: {{ include "notification-service.fullname" . }}-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: { }

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.postgresql.name }}
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}