apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.fullname" . }}-secret
type: Opaque
stringData:
  NOTIFICATION_DB_PASSWORD: {{ .Values.secrets.NOTIFICATION_DB_PASSWORD | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.NOTIFICATION_DB_PASSWORD | quote }}