apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend-service.fullname" . }}-secret
type: Opaque
stringData:
  FRONTEND_CLIENT_SECRET: {{ .Values.secrets.FRONTEND_CLIENT_SECRET | quote }}