spring:
  application:
    name: transfer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/Bank-app/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            jwk-set-uri: http://keycloak:8080/realms/Bank-app/protocol/openid-connect/certs
            authorization-uri: http://localhost:8080/realms/Bank-app/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/Bank-app/protocol/openid-connect/token
        registration:
          transfer-service:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: transfer-service
            client-secret: WOAP5tHHsAiWFK1MBJxYUEBryrPWckys
            scope: profile, openid
            clientAuthenticationMethod: client_secret_post
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka