apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocker-service.fullname" . }}-config
data:
  JWK_SET_URI: {{ .Values.config.JWK_SET_URI | quote }}
  ZIPKIN_URL: {{.Values.config.ZIPKIN_URL | quote}}