spring:
  application:
    name: blocker-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
server:
  port: 8087
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: prometheus