apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
data:
  AUTHORIZATION_URI: {{ .Values.config.AUTHORIZATION_URI | quote }}
  JWK_SET_URI: {{ .Values.config.JWK_SET_URI | quote }}
  TOKEN_URI: {{ .Values.config.TOKEN_URI | quote }}