DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS accounts;

CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    username   VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    birth_date DATE                                    NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS accounts
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    user_id  BIGINT                                  NOT NULL,
    currency VARCHAR(55)                             NOT NULL UNIQUE,
    amount   DECIMAL(10, 4)                          NOT NULL CHECK (amount >= 0),
    CONSTRAINT pk_accounts PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);