spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
      client:
        provider:
          keycloak:
            jwk-set-uri: ${JWK_SET_URI}
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
        registration:
          accounts-service:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: accounts-service
            client-secret: ${ACCOUNTS_CLIENT_SECRET}
            scope: openid, profile
            clientAuthenticationMethod: client_secret_post
  r2dbc:
    url: ${ACCOUNTS_DB_URL}
    username: ${ACCOUNTS_DB_USER}
    password: ${ACCOUNTS_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
keycloak:
  realmName: ${REALM_NAME}
  url: ${KEYCLOAK_URL}
  secret: ${ACCOUNTS_CLIENT_SECRET}
gateway:
  url: ${GATEWAY_URL}