spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/Bank-app/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

