spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
      client:
        provider:
          keycloak:
            jwk-set-uri: ${JWK_SET_URI}
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
        registration:
          cash-service:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: cash-service
            client-secret: ${CASH_CLIENT_SECRET}
            scope: profile, openid
            clientAuthenticationMethod: client_secret_post
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
gateway:
  url: ${GATEWAY_URL}
