spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
  data:
    redis:
      host: ${EXCHANGE_REDIS_HOST}
      port: ${EXCHANGE_REDIS_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}