replicaCount: 1

image:
  repository: cash-service
  tag: 1.0-SNAPSHOT
  pullPolicy: IfNotPresent

service:
  port: 8085

config:
  AUTHORIZATION_URI: http://localhost:8080/realms/Bank-app/protocol/openid-connect/auth
  JWK_SET_URI: http://keycloak:8080/realms/Bank-app/protocol/openid-connect/certs
  TOKEN_URI: http://keycloak:8080/realms/Bank-app/protocol/openid-connect/token
  GATEWAY_URL: http://api-gateway:8090/

secrets:
  CASH_CLIENT_SECRET: VoWW2PTF7LltBBZzTJc83Gu1fVA6EegX