replicaCount: 2

persistence:
  enabled: true
  size: 10Gi
  storageClass: "standard"

volumePermissions:
  enabled: true

zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 5Gi
    storageClass: "standard"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - kafka
        topologyKey: "kubernetes.io/hostname"
