apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exchange-generator-service.fullname" . }}-secret
type: Opaque
stringData:
  EXCHANGE_GENERATOR_CLIENT_SECRET: {{ .Values.secrets.EXCHANGE_GENERATOR_CLIENT_SECRET | quote }}