apiVersion: v2
name: bank-microservices
description: Umbrella chart for bank-microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: accounts-service
    version: "0.1.0"
    repository: "file://./charts/accounts-service"

  - name: blocker-service
    version: "0.1.0"
    repository: "file://./charts/blocker-service"

  - name: cash-service
    version: "0.1.0"
    repository: "file://./charts/cash-service"

  - name: exchange-generator-service
    version: "0.1.0"
    repository: "file://./charts/exchange-generator-service"

  - name: exchange-service
    version: "0.1.0"
    repository: "file://./charts/exchange-service"

  - name: frontend-service
    version: "0.1.0"
    repository: "file://./charts/frontend-service"

  - name: notification-service
    version: "0.1.0"
    repository: "file://./charts/notification-service"

  - name: transfer-service
    version: "0.1.0"
    repository: "file://./charts/transfer-service"

  - name: api-gateway
    version: "0.1.0"
    repository: "file://./charts/api-gateway"

  - name: kafka
    version: "0.1.0"
    repository: "file://./charts/kafka"

  - name: zipkin
    version: "0.1.0"
    repository: "file://./charts/zipkin"

  - name: prometheus
    version: "0.1.0"
    repository: "file://./charts/prometheus"

  - name: grafana
    version: "0.1.0"
    repository: "file://./charts/grafana"

  - name: logstash
    version: "0.1.0"
    repository: "file://./charts/logstash"

  - name: elasticsearch
    version: 0.1.0
    repository: "file://./charts/elasticsearch"

  - name: kibana
    version: 0.1.0
    repository: "file://./charts/kibana"