apiVersion: v2
name: grafana
description: grafana Helm chart
type: application
version: 0.1.0
appVersion: "4.0.0"

dependencies:
  - name: grafana
    version: 9.2.3
    repository: https://grafana.github.io/helm-charts